### ISSUE TITLE
个人介绍

### ISSUE THREAD

**Issue by xingbin321** [runwithcc/HTWAAG#4]
#### 个人介绍
- **姓名**：邢彬
- **微信昵称**：四月
- **Github登录邮箱**：48195904@qq.com
- **地区**： 昆明
- **行业**：文物保护
- **职位**：学生
- **个人网站**：无
- **个人标签**：选择恐惧症、寻找内心
- **参加活动的期待**：学习，进步，然后把这种坚实的力量传递给内心。

---- 
#### 小组信息
- **所在组名**：能量棒
- **本组组长**：四月
- **本组其他成员**：柴茝、团子、韩贤君
- **本组口号**：不忘初心，享受到达

**Comment by ruoxiaomu** [comment]
@xingbin321 回复错了哦，不在这里提交自我介绍。在[issue#3完成组队任务](https://github.com/runwithcc/HTWAAG/issues/3)下提交

**Comment by upgen** [comment]
我以为在这里
